language: node_js
sudo: true
node_js:
  - stable
cache:
  directories:
    - node_modules
before_install:
  - npm i
script:
  - npm run test
after_script:
  - npm run coverage
env:
  global:
    secure: "k8gZFxGSoGLJzoSHVrs2KJkA191ds5QJdokzEFlr+YEIntjWzEvQXJnHcwsrh0ZEWicNU1dFmERHR4Ts2NFy2/V8/JuLKp2UYRKGC6O2xykgz0VDAjKQgHrPsMoU54SdGjpmUQ7Cl47rqlml8oveiBA1gBaHH11ud+gkxzYafW0GMhsix6awq7DnXTbOrlIUgdDm/y/uEvAgCSADBqWu2ejCBX+QaAio1jdw7B+rOpdfzPTbXGI9bh9lqQmZfzdjbew1R1p8z7BxfpYSyJgHRnjBOoxIVZ2op3TMrfhCurm6znAYDMrBUreKbWJzFau7Wi4+wXykuqjjJOiYfaJHw6glouZ1dGGukDbXPr5394IVvgdNXZ2YUYbsXyRn4ljVKrqtRmaIoR0JXz3PDoMDVxbWW4sIMsaBSBif7z1zNeERo5uoAfh/hraREUBnIoW063aJr6qUzDbxEmEsB4i1NuIAcx0IGSuGwIonKeoUymE1u6ZUI95knawhXsV0T5QcqigcG81lfQhUtaicz94hzYhHgZLgg0TEzF2vBsZrMZfE4Kmd4MH5oxBkVYeHgDWrC4HMSi4oiv1Qr+OZnNVJcWwyRIsVQ4HP6Odl5LARnJQpVqJqtUdpPgQnZj0jrU9gxw4xPcfNzlac8KSpVG1whDtbNnYE1KuDVtEtppYCuo8="
